database:
  # Either MySQl or Sqlite
  type: MySQL
  host: localhost
  port: 3306
  database: dbName
  username: dbUser
  password: dbPass

## For mob stacking plugins, Should the stack be respected or just seen as 1 entity (for point calculation)
mobStackingCountAsOne: false

# Will spam the console with data if enabled
debug: false