name: UltimateSkills
version: 1.0
main: com.github.spiderjockey02.UltimateSkills
api-version: '1.20'
commands:
  skills:
    description: Your description
    usage: /<command>
    permission: ultimateskills.skills
